spring.application.name=e-learning

# 1. MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/elearning_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# 4. Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dsypmso4t}
cloudinary.api-key=${CLOUDINARY_API_KEY:257976411884745}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:0Dkm0yfiYEsMcMlUjytl30zMQ2A}

# 5. Upload file size
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
