spring.application.name=e-learning

# 1. MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/elearning_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# 4. Cloudinary
cloudinary.cloud-name=dsypmso4t
cloudinary.api-key=141769892663914
cloudinary.api-secret=5feS0CsuXj-TU_Up8Ebm1jkYyMY

# 5. Upload file size
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
