spring.application.name=e-learning

# 1. Cấu hình kết nối Laragon MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/elearning_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Cấu hình Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Cấu hình Swagger UI (để xem tài liệu API)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html